# Generated by Django 2.0.3 on 2018-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('name_fl', models.CharField(max_length=1)),
                ('type', models.SmallIntegerField()),
                ('embedding', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='item_name_index'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name_fl'], name='item_name_fl_index'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='item_type_index'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name_fl', 'type'], name='item_name_fl_type_index'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type', 'name_fl'], name='item_type_name_fl_index'),
        ),
    ]
